name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf DiopAmadou.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ HOST_DNS }}
        username: ${{ USERNAME }}
        key: ${{ KEY_SSH }}
        port: ${{ DEPLOY_PORT }}
        source: "DiopAmadou.war"
        target: "/opt/tomcat/webapps"
